### PR TITLE
Do not run release job for branch creation events

### PR DESCRIPTION
**Pull request by rpanderson**
Resolves item 1 in #8.

### CODE REVIEW

**Comment by rpanderson** [comment]
Merging, as the very creation of this feature branch resulted in the intended workflow of this PR.

**Comment by chrisjbillington** [comment]
Does the exit 1 make the workflow register as failed and send everyone emails?

**Comment by rpanderson** [comment]
> Does the exit 1 make the workflow register as failed...

Yes, I was testing this way of filtering branch creation events, using the `needs: github_properties` in the subsequent job of this workflow. I've since removed this and just put it in as a conditional.

> ... and send everyone emails?

Only if you have notifications configured to  do so.

**Comment by rpanderson** [comment]
See also my reply to [your earlier comment](https://github.com/labscript-suite/runviewer/commit/acd3240fa111e3bfec6795299afe0ac06f95f083#r39351961). This conditional is only required because I'm triggering the workflow with:
```yaml
on:
  push:
    branches:
      - master
      - maintenance/*
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
``` 
I do this because the attributes for tag creation events are more explicit than push events. See 'Aside' in #8. 

The triggering context of GitHub Actions is rather surprising/unexpected, e.g. the above triggers off branch creation events as well. The need for the conditional (now preceding the main job and not resulting in a failure) could be avoided altogether by only triggering off `push` events, but this requires further assumptions about branch names and reference text.

**Pull request merged**
